name: clean_architecture
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  retrofit: ^4.4.1
  analyzer: ^6.7.0
  dio: ^5.7.0
  json_serializable: ^6.8.0
  #json decoder
  retrofit_generator: ^9.1.5
  build_runner: ^2.4.13
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.5.2
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3
  device_info_plus: ^11.1.1
  freezed: ^2.5.7
  get_it: ^8.0.2
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
#     - assets/images/
#     - assets/json/
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/hollow_cirlce_ic.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/right_arrow_ic.svg
    - assets/images/solid_circle_ic.svg
    - assets/images/photo_camera_ic.svg
    - assets/images/settings_right_arrow_ic.svg
    - assets/images/change_lang_ic.svg
    - assets/images/contact_us_ic.svg
    - assets/images/invite_friends_ic.svg
    - assets/images/logout_ic.svg
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/success.json
    - assets/translations/



  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Montserrat-Medium.ttf
           weight: 500
         - asset: assets/fonts/Montserrat-Regular.ttf
           weight: 400
         - asset: assets/fonts/Montserrat-Light.ttf
           weight: 300
